folio-org/raml

README.md

Document the master locations of RAMLs

---

examples/moduleInfo.sample
ramls/tenant.raml
schemas/moduleInfo.schema

FOLIO-351 tidy 1

---

examples/tenantPermissions.sample
ramls/tenantPermissions.raml
schemas/errors.schema
schemas/tenantPermissions.schema

Fix processing issues with tenantPermissions.raml

DMOD-117 raml errors 1

---

schemas/README.md
schemas/error
schemas/parameters

Enables other RAML tools to operate

FOLIO-573 Add workaround symlink each referenced schema

---

examples/mod-users/group.sample
examples/mod-users/groups.sample
examples/mod-users/user.sample
examples/mod-users/user_collection.sample

Via Julian at
https://github.com/folio-org/mod-users/pull/26
https://github.com/folio-org/mod-users/pull/27

Update examples mod users 1

---

ramls/mod-users-bl/mod-users-bl.raml
schemas/mod-users-bl/compositeUser.json
schemas/mod-users-bl/compositeUserListObject.json

Whitespace changes only.
Was mostly 4-space but some 2-space.

FOLIO-351 tidy mod-users-bl

---

ramls/mod-users-bl/mod-users-bl.raml

Adjust parameters in RAML to match current code and README

FOLIO-601 Align raml mod-users-bl

---

ramls/mod-users-bl/mod-users-bl.raml
rtypes/attachments.raml
rtypes/item-collection.raml
schemas/mod-permissions/okapiPermission.json
schemas/mod-permissions/permissionUpload.json
schemas/mod-permissions/permissionUser.json
schemas/mod-users/addresstype.json
schemas/mod-users/addresstypeCollection.json
schemas/mod-users/userdata.json
schemas/mod-users/usergroup.json

FOLIO-351 tidy 3

---

examples/metadata.sample
schemas/metadata.schema

I think this is complete. 
David, I'd like your thoughts on how this interacts with RMB-30 as this schema will sit above all of the schema that reference it.

Add initial metadata schema for representing change summary information

---

schemas/mod-circulation/loan-policy.json

loan-policy.json is used by mod-circulation-storage and mod-circulation

CIRC-11: loan-policy.json resuse

---

examples/mod-users/addresstype.sample
examples/mod-users/addresstypeCollection.sample
schemas/mod-permissions/permission.json

FOLIO-351 whitespace tidy 3

---

ramls/mod-users-bl/mod-users-bl.raml
ramls/mod-users/addressTypes.raml
ramls/mod-users/groups.raml
ramls/mod-users/users.raml
traits/searchable.raml

This arises from a discussion with Seb and Heikki on the #staff channel. I don't know whether there are special requirements on the format of these parts of a RAML trait, so I'd like Shale to check this before merging.

Better description and example for the "searchable" trait

---

examples/mod-users/proxyfor.sample
examples/mod-users/proxyforCollection.sample
ramls/mod-users/proxiesFor.raml
schemas/mod-users/proxyfor.json
schemas/mod-users/userdata.json

Whitespace only. 
Reformatted JSON with jq

FOLIO-351 whitespace tidy 4

---

ramls/mod-users/groups.raml
ramls/mod-users/users.raml
schemas/mod-users/userdataCollection.json
schemas/mod-users/usergroup.json
traits/pageable.raml

resolves https://github.com/folio-org/mod-users/pull/40

merge of MODUSERS 36  and 37

---

PULL_REQUEST_TEMPLATE.md

Add a pull request template to the project, it will be provided each time a pull request is made to assist in documenting changes.
Approach was used in Frontside eHoldings application, functionality provided from GITHUB
https://github.com/blog/2111-issue-and-pull-request-templates
https://www.youtube.com/watch?v=5aHmO_S8FQ4

Add pull request template to help with documenting 

---

examples/codex/instance.sample
examples/codex/instanceCollection.sample
ramls/codex/codex.raml
schemas/codex/coverage.json
schemas/codex/coverageCollection.json
schemas/codex/instance.json
schemas/codex/item.json
schemas/codex/itemCollection.json
schemas/codex/location.json
schemas/codex/locationCollection.json
schemas/codex/package.json
schemas/codex/packageCollection.json

As per contribution guidelines.
Reformat JSON with jq.
Replace tabs with spaces.
Whitespace changes only.

FOLIO-351 whitespace tidy 5

---

ramls/codex/codex.raml

_Fix raml-cop complaints._
_Removed unused schema references_

Fix raml-cop complaints

---

ramls/mod-users-bl/mod-users-bl.raml
schemas/compositeUser.json

Update mod-user-bl raml to support proxiesFor in mod-users

Update to support proxiesFor in mod-users-bl compositeUser record

---

ramls/codex/codex.raml

Update project name from mod-kb-ebsco-codex to mod-codex-ekb in the baseURI.

Update project name from mod-kb-ebsco-codex to mod-codex-ekb

---

schemas/CQLSchema.schema
schemas/codex/codex_instance_cqlschema.json

Ready to merge.
Fixed broken JSON, spurious comma.
Whitespace tidy.

Fix schema 1

---

schemas/CQLSchema.schema
schemas/codex/codex_instance_cqlschema.json

Add support for modifiers and add type=isbn|issn modifiers to the identifier index

Cql schema

---

schemas/metadata.schema

Was missing upper-case in first segment.

FOLIO-972 Improve UUID-like regex

---

examples/codex/instance.sample
examples/codex/instanceCollection.sample
schemas/codex/instance.json

Add descriptions for many fields, and enum for "type"

---

schemas/codex/codex_instance_cqlschema-ext.json

These values adhere to our https://docs.google.com/spreadsheets/d/1s4cMdQEThNH4v-3VpyoNpsZkY3uB1OGomQ99L2o5uVA/edit#gid=0 per our previous conversation.

Update schema for selected index to be all, true or false

---

schemas/codex/instance.json
schemas/codex/instanceCollection.json

Do not allow additional properties.
add "additionalProperties": false

Do not allow additional properties.

---

schemas/codex/instance.json

Per Khalilah's and Charlotte's latest discussion, they created a normalized list of resource types and documented here: https://docs.google.com/spreadsheets/d/1RRLjsTl-SMGEh-5RkVwguffKW4dvkO-IwTdca6kFXeE/edit#gid=667989703 in tab 4. Updating json accordingly

Update type enum to match latest discussions

---

schemas/codex/codex_instance_cqlschema.json

Extend CODEX schema with contributor and language

Add contributor and language

---

schemas/codex/codex_instance_cqlschema.json

classification index (implementable for local inventory)

Add classification filter

---

examples/codex/instanceCollection.sample
ramls/codex/codex.raml
schemas/codex-next/coverageCollection.json
schemas/codex-next/itemCollection.json
schemas/codex-next/locationCollection.json
schemas/codex-next/packageCollection.json
schemas/codex/instanceCollection.json
schemas/resultInfo.schema

Modcxmux 7

---

examples/codex/instanceCollection.sample
schemas/codex-next/coverageCollection.json
schemas/codex-next/itemCollection.json
schemas/codex-next/locationCollection.json
schemas/codex-next/packageCollection.json
schemas/codex/codex_instance_cqlschema.json
schemas/codex/instanceCollection.json
schemas/resultInfo.schema

Use consistent indent.
Whitespace changes only.

FOLIO-351 whitespace tidy 8

---

schemas/resultInfo.schema

Add recordCount, module and query within diagnostics MODCXMUX-14

---

schemas/mod-users/usergroup.json

Remove 'desc' from required fields in usergroup schema

---

schemas/mod-users/proxyfor.json
schemas/mod-users/userdata.json

FOLIO-351 whitespace tidy 9

---

schemas/mod-permissions/permission.json

FOLIO-351 whitespace tidy 10

---

ramls/mod-permissions/tenantPermissions.raml

Add validation trait to tenant permissions raml

---

ramls/mod-permissions/tenantPermissions.raml

Add parameters schema to tenantPermissions raml

---

ramls/mod-permissions/permissions.raml
schemas/mod-permissions/permission.json

Allow for permissions to be flagged as 'dummy'

---

scripts/lint-raml-cop.sh

Find and process raml files, schema, and examples.
Report issues and lead to help.
Provides ./scripts/lint-raml-cop.sh
https://dev.folio.org/guides/raml-cop

FOLIO-1027 Add scripts/lint-raml-cop.sh

---

CONTRIBUTING.md
README.md
traits/searchable.raml

Link to new URLs at dev.folio.org
Edited and verified all such links.

FOLIO-1179 fix dev.f.o URLs

---

ramls/mod-users/addressTypes.raml
schemas/mod-users/addresstype.json
schemas/mod-users/userdata.json

Make 'username' option for users. Add metadata to addressTypes

---

examples/tagged-record-example/user.sample
examples/tagged-record-example/user_collection.sample
examples/tags.sample
ramls/tagged-record-example/users.raml
schemas/tagged-record-example/userdata.json
schemas/tagged-record-example/userdataCollection.json
schemas/tags.schema

Allow records to be tagged with 0 or more tags
Introduce a new tag schema (thanks Heikki) and provide an example of usage in a record (see tagged-record-example, based upon users)

Example Use of Tags

---

schemas/mod-users/userdata.json

Add tags to the user record (userdata.json)

Add tags to the user record (userdata.json)

---

schemas/mod-users/proxyfor.json

Proxy for meta

---

schemas/mod-users/proxyfor.json

Remove 'meta' field from proxyfor schema

---

schemas/mod-permissions/permissionUser.json

Add metadata field to permission user

---

ramls/mod-login/login.raml
schemas/mod-login/updateCredentials.json

Update raml/schema to support mod-login update

---

schemas/mod-permissions/permissionUpload.json

Add metadata field to permissionsUpload schema

---

ramls/mod-login/login.raml
schemas/mod-login/loginAttempts.json

Add entities for MODLOGIN-41  Handling: Failed login attempts - Lock Account

MODLOGIN-41  Handling: Failed login attempts - Lock Account

---

Jenkinsfile

This enables lint-raml in CI.
Also only do publishAPI when master branch.

FOLIO-1027 enable lint-raml jenkins 2

---

ramls/tagged-record-example/users.raml
schemas/codex/instance.json
schemas/codex/instanceCollection.json
schemas/tagged-record-example/userdata.json
schemas/tagged-record-example/userdataCollection.json

Add some JSON schema descriptions to "raml1.0" branch.

FOLIO-1554 schema descriptions 1
